openapi: 3.2.0
info:
  title: Reference Intent API
  description: The Reference API is used to retrieve reference data that is used throughout Bombora's APIs.
  version: 1.0.1
servers:
- url: https://api.bombora.com/reference/v1
security:
- bearerAuth: []
tags:
- name: Intent
paths:
  /topics:
    get:
      tags:
      - Intent
      summary: Returns a list of topics with optional filtering by attributes
      description: 'This endpoint returns a collection of intent topics, each with detailed information including id, name, theme, and category.


        Filtering:

        The list of topics can be filtered using query parameters, allowing for dynamic topic retrieval without loading the full list of topics. Each filter is applied independently with OR logic, meaning a topic will be included if it matches any of the specified criteria. Filters accept multiple comma-separated, case-insensitive values, providing flexibility for broad and inclusive searches.'
      parameters:
      - name: id
        in: query
        description: Filters results by topic IDs. Accepts a comma-separated list of IDs, returning topics that match any of the specified IDs.
        required: false
        schema:
          type: string
        examples:
          Return topics by ID matching:
            value: 1505708,1502758
            summary: Return all topics with ID of 1050708 or 10502758
      - name: name
        in: query
        description: Filters results by topic name. Accepts a comma-separated list of strings, returning topics where the name contains any of the specified strings (case-insensitive).
        required: false
        schema:
          type: string
        examples:
          Return topics by name search:
            value: Exchange,Finance
            summary: Return all topics with a name that contains "Exchange" or "Finance" (case-insensitive)
      - name: theme
        in: query
        description: Filters results by topic theme. Accepts a comma-separated list of strings, returning topics where the theme contains any of the specified strings (case-insensitive).
        required: false
        schema:
          type: string
      - name: category
        in: query
        description: Filters results by topic category. Accepts a comma-separated list of strings, returning topics where the category contains any of the specified strings (case-insensitive).
        required: false
        schema:
          type: string
      - name: description
        in: query
        description: Filters results by topic description. Accepts a comma-separated list of strings, returning topics where the description contains any of the specified strings (case-insensitive).
        required: false
        schema:
          type: string
        examples:
          Return topics by description search:
            value: SEC
            summary: Return all topics with a description  that contains "SEC" (case-insensitive)
      - name: s
        in: query
        description: Returns similar topics. Accepts a comma-separated list of IDs, returning topics that are similar to the topics represented by the specified IDs. By default, up to 50 topics are returned. This limit can be modified by the 'maxTopics' parameter.
        required: false
        schema:
          type: string
        examples:
          Example with similar topic filtering:
            value: 1505708,1502758
            summary: The topic is similar to topic 1505708 or 1502758
      - name: maxTopics
        in: query
        description: Modifies the maximum number of topics returned when the 's' query parameter is used.
        required: false
        schema:
          type: integer
      responses:
        '200':
          description: Success - The response body includes the requested resource.
          content:
            application/json:
              schema:
                type: object
                properties:
                  topics:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          format: int32
                          description: The unique identifier of the topic.
                        name:
                          type: string
                          description: The name of the topic.
                        theme:
                          type: string
                          description: The theme to which the topic belongs.
                        category:
                          type: string
                          description: The category to which the topic belongs.
                        description:
                          type: string
                          description: Provides a detailed description of the topic.
              example:
                topics:
                - id: 1333532
                  name: Local Government
                  theme: Government
                  category: Other
                  description: The administration of a particular town, county, or district, with representatives elected by those who live there.
                - id: 1333536
                  name: Legal
                  theme: Legal
                  category: Legal Services
                  description: Of, based on, or concerned with the law.
        '400':
          $ref: '#/components/responses/BadRequestError'
        '422':
          $ref: '#/components/responses/UnprocessableEntityError'
      operationId: getTopics
      x-operation-id-source: derived
  /b2c-interest:
    get:
      tags:
      - Intent
      summary: Returns a list of topic attributes related to B2C interest
      description: Returns a list of supported B2C Interest Attributes. B2C interest represents the B2C topics a given device has shown interest in.
      responses:
        '200':
          description: Success - The response body includes the requested resource.
          content:
            application/json:
              schema:
                type: object
                properties:
                  b2cInterest:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                          description: The name of the B2C interest topic.
              example:
                b2cInterest:
                - name: Acura
                - name: Aston Martin
                - name: Audi
                - name: Baseball
                - name: Basketball
                - name: Bentley
                - name: BMW
                - name: Boats and Watercraft
                - name: Organic Foods
                - name: Parenting
                - name: Peugeot
                - name: Photography
                - name: Wine
                - name: Yoga
        '400':
          $ref: '#/components/responses/BadRequestError'
        '422':
          $ref: '#/components/responses/UnprocessableEntityError'
      operationId: getB2cInterest
      x-operation-id-source: derived
  /b2b-interest-groups:
    get:
      tags:
      - Intent
      summary: Returns a list of B2B interest group attributes
      description: Returns a list of supported B2B Interest Attributes. B2B interest represents the B2B topics (from Bombora’s Topic Taxonomy) a given device has shown interest in.
      responses:
        '200':
          description: Success - The response body includes the requested resource.
          content:
            application/json:
              schema:
                type: object
                properties:
                  b2bInterestGroups:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                          description: The name of the B2B interest group.
              example:
                b2bInterestGroups:
                - name: Accounting
                - name: Administration
                - name: Agencies & Branding
                - name: Application & Software Development
                - name: Benefits
                - name: Budgeting, Planning & Strategy
                - name: Business Analytics & Applications
                - name: Capital Procurement
                - name: Networking & VOIP
                - name: Online Advertising
                - name: Training & Development
                - name: Virtualization
                - name: Website Publishing
        '400':
          $ref: '#/components/responses/BadRequestError'
        '422':
          $ref: '#/components/responses/UnprocessableEntityError'
      operationId: getB2bInterestGroups
      x-operation-id-source: derived
  /demographic/b2b-personas:
    get:
      tags:
      - Intent
      summary: Returns a list of B2B persona attributes
      description: This endpoint returns a collection of B2B persona's which represent demographic attributes and are used to identify employees showing positive Intent.
      responses:
        '200':
          description: Success - The response body includes the requested resource.
          content:
            application/json:
              schema:
                type: object
                properties:
                  b2bPersonas:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                          description: The name of the persona.
              example:
                b2bPersonas:
                - name: Board and Ownership
                - name: Consultants
                - name: C-Suite
                - name: Education
                - name: Engineering
                - name: Finance
                - name: Finance Decision Maker
                - name: Government
                - name: HR Decision Maker
                - name: Human Resources
                - name: Information Technology
                - name: IT Decision Maker
                - name: Legal
                - name: Management
                - name: Marketing
                - name: Marketing Decision Maker
                - name: Operations
                - name: Sales
                - name: Software and Web Development
        '400':
          $ref: '#/components/responses/BadRequestError'
        '422':
          $ref: '#/components/responses/UnprocessableEntityError'
      operationId: getDemographicB2bPersonas
      x-operation-id-source: derived
components:
  responses:
    BadRequestError:
      description: The request is syntactically invalid.
    UnprocessableEntityError:
      description: The request body is syntactically correct but semantically incorrect, such as validation errors.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorMessageResponse'
  schemas:
    ErrorMessageResponse:
      type: object
      properties:
        message:
          type:
          - string
          - 'null'
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
