openapi: 3.2.0
info:
  title: Webhooks Events API
  description: The Webhooks API provides the ability to create webhook destinations for receiving various Bombora event subscriptions.
  version: 1.0.1
servers:
- url: https://api.bombora.com/webhooks/v1
security:
- bearerAuth: []
tags:
- name: Events
paths:
  /destination/{destinationId}/events:
    get:
      tags:
      - Events
      description: Returns list of subscribable events, along with a status.
      parameters:
      - $ref: '#/components/parameters/destinationId'
      responses:
        '200':
          description: Success - The destinations were successfully retrieved.
          content:
            application/json:
              schema:
                type: object
                properties:
                  events:
                    type: array
                    description: A list of subscribable events types and their current status.
                    items:
                      type: object
                      properties:
                        eventType:
                          type: string
                          description: Name of the event type.
                          example:
                            eventType: SignalDefinitionCreated
                        enabled:
                          description: True if event type is enabled, otherwise false.
                          type: boolean
                          example:
                            enabled: true
              example:
                events:
                - eventType: SignalDefinitionCreated
                  enabled: true
                - eventType: SignalDefinitionUpdated
                  enabled: false
                - eventType: SignalDefinitionDeleted
                  enabled: false
                - eventType: AccountListAccountsUpdated
                  enabled: true
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        '404':
          $ref: '#/components/responses/NotFoundError'
      security:
      - bearerAuth: []
      summary: Get destination by destination id events
      x-summary-source: derived
      operationId: getDestinationByDestinationIdEvents
      x-operation-id-source: derived
  /destination/{destinationId}/event/{eventType}:
    get:
      tags:
      - Events
      description: Retrieve the configuration and related stats for the specified event type.
      parameters:
      - $ref: '#/components/parameters/destinationId'
      - $ref: '#/components/parameters/eventType'
      responses:
        '200':
          description: Success - The response body includes the requested resource.
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/Event'
                - $ref: '#/components/schemas/stats'
              examples:
                Example return for an event that has been subscribed to:
                  summary: Example return for an event that has been subscribed to.
                  value:
                    enabled: true
                    headers:
                      X-Message-Type: signal-is-ready
                    stats:
                      successful: 94
                      failed: 4
                      lastError: 401 Unauthorized
                      lastErrorAction: Retried
                      lastErrorTimestamp: '2023-09-05 15:22:04Z'
                Example an event with no subscriptions enabled:
                  summary: If event exists, but has never been subscribed to; or, subscription has been deleted, endpoint returns.
                  value:
                    enabled: false
                    headers: {}
                    stats: {}
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        '404':
          $ref: '#/components/responses/NotFoundError'
      security:
      - bearerAuth: []
      summary: Get destination by destination id event by event type
      x-summary-source: derived
      operationId: getDestinationByDestinationIdEventByEventType
      x-operation-id-source: derived
    put:
      tags:
      - Events
      description: Replaces the event document for the specified webhook destination.
      parameters:
      - $ref: '#/components/parameters/destinationId'
      - $ref: '#/components/parameters/eventType'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Event'
            example:
              enabled: true
              headers:
                X-Message-Type: signal-is-ready
      responses:
        '200':
          description: Success - The request has been processed successfully.
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '422':
          $ref: '#/components/responses/UnprocessableEntityError'
      security:
      - bearerAuth: []
      summary: Replace destination by destination id event by event type
      x-summary-source: derived
      operationId: putDestinationByDestinationIdEventByEventType
      x-operation-id-source: derived
    delete:
      tags:
      - Events
      description: Deletes the event from the subscription list.
      parameters:
      - $ref: '#/components/parameters/destinationId'
      - $ref: '#/components/parameters/eventType'
      responses:
        '200':
          description: The resource no longer exists.
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        '404':
          $ref: '#/components/responses/NotFoundError'
      summary: Delete destination by destination id event by event type
      x-summary-source: derived
      operationId: deleteDestinationByDestinationIdEventByEventType
      x-operation-id-source: derived
components:
  schemas:
    ErrorMessageResponse:
      type: object
      properties:
        message:
          type:
          - string
          - 'null'
    stats:
      type: object
      description: Stats related to the event type subscription.
      properties:
        successful:
          description: Count of successful posts of event to destination.
          type: integer
        failed:
          description: Count of failed posts of event to destination.
          type: integer
        lastError:
          description: Error message for last failed event post.
          type: string
        lastErrorAction:
          description: Action taken upon last failure of event post.
          type: string
        lastErrorTimestamp:
          description: Timestamp of last event post failure.
          type: string
    Event:
      type: object
      properties:
        enabled:
          description: True if event type is enabled; otherwise, false.
          type: boolean
        headers:
          type: object
          description: Expected headers to receive when event type is triggered.
          additionalProperties:
            type: string
  parameters:
    eventType:
      name: eventType
      in: path
      required: true
      schema:
        type: string
        example:
          SignalDefinitionCreated: null
    destinationId:
      name: destinationId
      in: path
      required: true
      description: An identifier for the destination.
      schema:
        type: string
        format: uuid
      example: 3fa85f64-5717-4562-b3fc-2c963f66afa6
  responses:
    ForbiddenError:
      description: The access token does not have permission to access this API.
    UnprocessableEntityError:
      description: The request body is syntactically correct but semantically incorrect, such as validation errors.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorMessageResponse'
    UnauthorizedError:
      description: The access token is missing or invalid.
    NotFoundError:
      description: The resource could at this path does not exist.
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
